[tool.poetry]
name = "Fable Python"
version = "4.0.0"
description = "Fable"
authors = ["Dag Brattli <dag@brattli.net>"]
license = "MIT License"
readme = "README.md"
homepage = "https://fable.io"

[tool.poetry.dependencies]
python = ">= 3.9, < 4.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = {version = "^22.6.0", allow-prereleases = true}

[tool.pyright]
reportMissingTypeStubs = false
reportMissingImports = false
reportUnnecessaryTypeIgnoreComment = true
reportUnusedImport = true
reportUnusedVariable = true
reportUnnecessaryIsInstance = true
reportUnnecessaryComparison = true
reportUnnecessaryCast = true
reportPrivateUsage = true
reportImportCycles = true
reportDuplicateImport = true
reportConstantRedefinition = true
reportOverlappingOverload = true
reportInconsistentConstructor = true
reportImplicitStringConcatenation = true
pythonVersion = "3.10"
typeCheckingMode = "basic"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
